name: Second Workflow
on:
  workflow_run:
    workflows: [First Workflow]
    types:
      - completed

  workflow_dispatch:
  
jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print previous job status
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Print trigger
        run: echo "${{ toJson(github.event.name) }}"
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hey from second job!"
      - name: Print Goodbye
        run: echo "Bye from second job!"
