name: Second Workflow
on:
  workflow_run:
    workflows: [First Workflow]
    types:
      - completed

  workflow_dispatch:
  
jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Print Previous Steps Conclusion Via Event workflow run
        env:
          GITHUB_CONCLUSION: ${{ toJson(github.event.workflow_run.conclusion) }}
        run: |
          echo "$GITHUB_CONCLUSION"
      - name: Print Trigger from github event_name
        env:
          CONCLUSION: ${{ toJson(github.event_name) }}
        run: |
          echo "$CONCLUSION"
      - name: Print Trigger from github event name
        env:
          CONCLUSION2: ${{ toJson(github.event.name) }}
        run: |
          echo "$CONCLUSION2"
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hey from second job!"
      - name: Print Goodbye
        run: echo "Bye from second job!"
