name: Second Workflow
on:
  workflow_run:
    workflows: [First Workflow]
    types:
      - completed

  workflow_dispatch:
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Previous Workflow Status
        env:
          PREV_WORKFLOW_STATUS: ${{ toJson(github.event.workflow_run.conclusion) }}
        run: |
          echo "$PREV_WORKFLOW_STATUS"
      - name: Set Workflow Trigger
        env:
          WORKFLOW_TRIGGER: ${{ toJson(github.event_name) }}
        run: |
          echo "$WORKFLOW_TRIGGER"
      - name: Pass or Fail Job Based on Previous Workflow
        if: ${{ (github.event_name == 'workflow_run') && (github.event.workflow_run.conclusion == 'failure') }}
        run: |
          echo "Previous workflow failed"
          core.setFailed
        
  second-job:
    needs:
      - first-job
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hey from second job!"
      - name: Print Goodbye
        run: echo "Bye from second job!"
